/** @type {import('tailwindcss').Config} */
module.exports = {
	plugins: [],
	content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
	theme: {
		colors: {
			'primary': 'rgb(var(--color-primary, <alpha-value>))',
			'primary-light': 'rgb(var(--color-primary-light, <alpha-value>))',
			'primary-dark': 'rgb(var(--color-primary-dark, <alpha-value>))',
			'primary-details': 'rgb(var(--color-primary-details, <alpha-value>))',
			'secondary': 'rgb(var(--color-secondary, <alpha-value>))',
			'secondary-light': 'rgb(var(--color-secondary-light, <alpha-value>))',
			'secondary-dark': 'rgb(var(--color-secondary-dark, <alpha-value>))',
			'secondary-extra-light': 'rgb(var(--color-secondary-extra-light, <alpha-value>))',
			'secondary-details': 'rgb(var(--color-secondary-details, <alpha-value>))',
			'surface': 'rgb(var(--color-surface, <alpha-value>))',
			'surface-dark': 'rgb(var(--color-surface-dark, <alpha-value>))',
			'surface-light': 'rgb(var(--color-surface-light, <alpha-value>))',
			'error': 'rgb(var(--color-error, <alpha-value>))',
			'success': 'rgb(var(--color-success, <alpha-value>))',
			'warning': 'rgb(var(--color-warning, <alpha-value>))',
			'accent': 'rgb(var(--color-accent, <alpha-value>))',
			'disabled': 'rgb(var(--color-disabled, <alpha-value>))',
			'on-primary': 'rgb(var(--color-on-primary, <alpha-value>))',
			'on-primary-light': 'rgb(var(--color-on-primary-light, <alpha-value>))',
			'on-primary-dark': 'rgb(var(--color-on-surface-light, <alpha-value>))',
			'on-primary-details': 'rgb(var(--color-on-primary-details, <alpha-value>))',
			'on-secondary': 'rgb(var(--color-on-secondary, <alpha-value>))',
			'on-secondary-light': 'rgb(var(--color-on-secondary-light, <alpha-value>))',
			'on-secondary-dark': 'rgb(var(--color-on-secondary-dark, <alpha-value>))',
			'on-secondary-details': 'rgb(var(--color-on-secondary-details, <alpha-value>))',
			'on-surface': 'rgb(var(--color-on-surface, <alpha-value>))',
			'on-surface-dark': 'rgb(var(--color-on-surface-dark, <alpha-value>))',
			'on-surface-light': 'rgb(var(--color-on-surface-light, <alpha-value>))',
			'on-error': 'rgb(var(--color-on-error, <alpha-value>))',
			'on-success': 'rgb(var(--color-on-success, <alpha-value>))',
			'on-warning': 'rgb(var(--color-on-warning, <alpha-value>))',
			'on-accent': 'rgb(var(--color-on-accent, <alpha-value>))',
			'on-disabled': 'rgb(var(--color-on-disabled, <alpha-value>))',
		},
		extend: {},
	},
};
